### ISSUE TITLE
Xamarin Studio 6.0

### ISSUE THREAD

**Issue by cornelha** [grbd/GBD.Blog.Examples#1]
Xamarin Studio 6.0 negates having to jump through all these hoops. Not only is the IDE free but has a native GTK designer built in. Full intellisense and built in git client included. You might want to revisit your tutorial
![xamstudio](https://cloud.githubusercontent.com/assets/1282205/16652202/38aa2eba-4449-11e6-9fc5-1a8b9e3e44e2.PNG)

**Comment by Hecatron** [comment]
There's a few reasons why I avoided Xamarin Studio
- I believe Xamarin Studio uses an editor called Stetic for gtk apps. This info might be out of date, but I think Stetic only supports gtk2 not gtk3 looking at this link
  http://mono.1490590.n4.nabble.com/Stetic-GUI-Designer-Move-to-Glade-for-Gtk-3-td4662883.html
- The next reason is that I prefer the addins within Visual Studio such as resharper.

The aim of the tutorial was to show how to get the latest gtk3 / gtksharp3 working instead of gtk2
My eventual plan is to create applications using .Net Core and gtksharp (possibly via eto.forms).
sice eto.forms can use gtksharp as its back end but also allow for the use of xaml

**Comment by Hecatron** [comment]
closing as Xamarin Studio only uses gtk2 for its gui designer, this relates to gtk3 / gtksharp 3
